### ISSUE TITLE
PowerShell cmdlets/variables don't work with non-portable Playnite installs

### ISSUE THREAD

**Issue by pathartl** [LANCommander/LANCommander#45]

**Comment by puffnfresh** [comment]
I have this problem right now. On my install, Playnite is at `%LocalAppData%\Playnite\Playnite.DesktopApp.exe`. The LANCommander PowerShell module is at `%AppData%\Playnite\Extensions\LANCommander.PlaynitePlugin_48e1bac7-e0a0-45d7-ba83-36f5e9e959fc\LANCommander.PowerShell.psd1`.

Copying that file and the associated DLL to `%LocalAppData%\Playnite` makes things work, due to your fix.

It would probably be better to programmatically resolve the extension directory. Does the Playnite extension API expose that?

**Comment by pathartl** [comment]
It does, but v1.0.0 is on the way and the Playnite plugin will soon be deprecated in favor of the new launcher.
