### ISSUE TITLE
SteamGridDB Missing Icons

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#48]
![msedge_pgn83MeQpu](https://github.com/LANCommander/LANCommander/assets/5581855/14dbc6f0-8be8-41d2-965d-bd094c568751)

Sometimes the SteamGridDB section is missing Icons, even though SteamGridDB has them.

**Comment by pathartl** [comment]
Will be fixed in the next release. Had to have a bit of a compromise... we can't process .ico files currently without requiring Windows, thus they were excluded from acceptable file types.

The change implemented will use the thumbnail from SteamGridDb (which is probably a PNG) instead of the source .ico file.
