### ISSUE TITLE
0.7.2 resolves only part of the problem-

### ISSUE THREAD

**Issue by fdgfsfdgsfg** [LANCommander/LANCommander#64]
Hi,

Expansions and mods now download as intended, with just a small UI bug while it downloads either the expansions or the mods - it does not show the progress or internet speed. 

The main problem now is that the expansions and mods do not appear as selectable options upon pressing "Play" on the base game. It simply starts the base game.

**Comment by pathartl** [comment]
The builds I handed you in Discord were for testing, they weren't official release builds. I don't have any way to pass dev builds through GitHub and since I don't see you in the Discord anymore, I've published 0.7.2 which should fix both the download and list of actions for expansions/mods. This isn't well tested so consider it experimental.

Currently there is no way to display the progress of mods/expansions being installed without a larger code change. It may be investigated in the future but meeting basic implementation is more important.
