### ISSUE TITLE
Expansions/mods issues

### ISSUE THREAD

**Issue by dalbitresb12** [LANCommander/LANCommander#66]
Hello, I've been trying out LANCommander and I've been loving it so far.

I've found some issues with the expansions/mods during my testing:

- **The scripts of expansions/mods are not run**: I found after some testing that the endpoint `/api/Games/{id}` doesn't set `BaseGame` for `DependentGames`, which makes complete sense since that would create a circular dependency. The problem appears when running functions like [`DownloadQueueController.RunInstallScript`](https://github.com/LANCommander/LANCommander/blob/651cc4d439fe9857f2a1254c2508a5ec11cf4ce5/LANCommander.Playnite.Extension/DownloadQueueController.cs#L455-L478), which end up using [`GameService.GetInstallDirectory`](https://github.com/LANCommander/LANCommander/blob/651cc4d439fe9857f2a1254c2508a5ec11cf4ce5/LANCommander.SDK/GameService.cs#L392-L398) and without the `BaseGame` set, that function returns a non-existent folder as if the expansion/mod were a standalone game on its own folder.
	- For example, if we had game `Game 1` as the base game and `Game 1: DLC 1` as an expansion, the function would look for the scripts in the folder `C:\Games\Game 1 - DLC 1\.lancommander\{expansion_id}\Script.ps1` instead of `C:\Games\Game 1\.lancommander\{expansion_id}\Script.ps1`
	- I temporarily patched this in commit https://github.com/dalbitresb12/LANCommander/commit/6641069c4a5883a4a9fe20b39ef881a11e9729e3, but I'm not sure if this is the best way to do it.
- **Expansions/mods are not uninstalled**: I noticed that the files for these types are not removed after uninstalling the base game, potentially leaving behind GBs of unnecessary files.
	- I've also temporarily patched this in https://github.com/dalbitresb12/LANCommander/commit/a8a488712f928458586b59457b83566a197c6f74
	- My patch also (maybe?) includes a breaking change: it reverses the order in which the uninstall scripts are run. First expansions/mods, then base game.
- **Unable to launch game with expansions/mods**: Whenever there's a game with an expansion/mod that doesn't include a game action, Playnite is unable launch the game, with a text box saying there's no valid game action.
	- I temporarily solved this by adding a dummy action to the expansion and unchecking the `Primary` checkbox so that it doesn't prompt the user to select which action to launch.
	- I still haven't found why this happens. Not sure if this is a LANCommander plugin or Playnite problem.
- **All the expansions/mods are installed by default**: This is mostly a feature request, to be honest. I would love a way to select which expansions/mods should be installed when installing the base game, and also be able to add/remove which ones I currently have installed.
	- I'm taking inspiration from how Steam manages DLCs, as you can see in [this screenshot](https://github.com/LANCommander/LANCommander/assets/7624090/5cee1b1f-69f8-43c6-9c3a-eeb818d47035) from my Rocksmith DLCs.
	- I might work on this feature if you're interested in something like this.

Let me know if you're interested in me submitting my patches as PRs (not sure if you want two separate PRs or just one) and if I should work on the feature request I sneaked at the end.

I'm happy to provide any log files if you're unable to reproduce the issues on your end.

**Comment by pathartl** [comment]
Thank you for the detailed report.

> I temporarily patched this in commit https://github.com/dalbitresb12/LANCommander/commit/6641069c4a5883a4a9fe20b39ef881a11e9729e3, but I'm not sure if this is the best way to do it.

I don't have any real issue with this. Like you said, avoiding circular references in transmission from the server would be best, and I think the only other way to do it would be to add an `installDirectory` parameter to `RunInstallScript` and the like, and I don't think we need to do that right now.

> My patch also (maybe?) includes a breaking change: it reverses the order in which the uninstall scripts are run. First expansions/mods, then base game.

Good catch. This looks good to me.

> Unable to launch game with expansions/mods: Whenever there's a game with an expansion/mod that doesn't include a game action, Playnite is unable launch the game, with a text box saying there's no valid game action. 

When manifest actions are looped through in `LANCommanderLibraryPlugin.GetPlayActions`, there's was no check done to make sure that `manifest.Actions` is not null. If an expansion/mod did not have any actions defined, it would throw an unhandled exception, resulting in the no play actions found error. This has been fixed with commit de89075463535a177bc106bb909bce642dac6cfa

> This is mostly a feature request, to be honest. I would love a way to select which expansions/mods should be installed when installing the base game, and also be able to add/remove which ones I currently have installed

This is absolutely something that can be expanded upon (and something I had planned on looking into), but there is work being done to replace the Playnite extension with a custom launcher. I'm kind of pushing the limit of what you should be doing with the Playnite API as is, and features such as updates have been increasingly hard to implement. Absolutely interested in the feature, but wouldn't want any work to be thrown away after a few months.

For the patches you mentioned here, please submit a PR and we can roll it into 0.7.4!

**Comment by dalbitresb12** [comment]
Awesome, I'll submit the patches in a bit.

> This has been fixed with commit https://github.com/LANCommander/LANCommander/commit/de89075463535a177bc106bb909bce642dac6cfa

Thank you for fixing that! I tried looking into how to fix that, but I had no idea how that worked.

> but there is work being done to replace the Playnite extension with a custom launcher

I'd love that! Is there any tracking issue or any discussion on that? I'd love to see any progress or contribute to it in any way I can.

**Comment by pathartl** [comment]
Not currently, no. It's extremely bare bones at the moment and private, but if more people are jumping on board discussion will probably happen in the Discord.
